### ISSUE TITLE
xmrig build on Ubuntu 19.10 ARMv8

### ISSUE THREAD

**Issue by esrrhs** [DocDrydenn/xmrig-build#3]
Hi, I have a raspberry 3B+, and the OS is Ubuntu 19.10. and when I use your script to build xmrig, it will use a large memory when compile RxDataset.cpp. and will not stop compiling even when I wait few days. do you know why and can you help me with this problem?

**Comment by DocDrydenn** [comment]
Sorry for such a long delay in responding... I didn't know anyone actually used this script other than me.

As for your build problems, I wish I could help, however, my script is just a helper script. It just does the tedious and cosmetic parts.

All of the building/compiling steps in my script are from the actual xmrig github instructions, so any questions involving the build/compile process will need to be directed back to the xmrig github.

Again, sorry for the delay in responding.

**Comment by esrrhs** [comment]
thanks for your reply, I fixed it and forgot how to fixed it. :)
