### ISSUE TITLE
can this script build xmrig static for armv7 and armv8?

### ISSUE THREAD

**Issue by novazz** [DocDrydenn/xmrig-build#4]

**Comment by DocDrydenn** [comment]
Honestly didn't think anyone still used this. Anyway...

Give v1.20 (latest) a try and see if it will build static for you (use the new `-s` flag).
(example: `./xmrig-build -8 -s`)

I've only had time to code and test on a x86-64 platform. I'll test ARM as soon as I get a chance.

**Comment by DocDrydenn** [comment]
I have been able to test on ARMv7 and ARMv8 hardware. Both dynamic and static builds were successful.

The only issues I encountered was when testing on Raspbian 9 and Raspberry Pi OS (I've updated the README to reflect). I am not sure why, but both dynamic and static builds will fail. My testing has convinced me that this is something OS related and outside of my script... so I will consider this issue closed.

Feel free to open a new issue if you run across any other issues.
