### ISSUE TITLE
Android Build

### ISSUE THREAD

**Issue by sradityaa** [DocDrydenn/xmrig-build#8]
Is it possible to build on Android without Ubuntu/Linux?

**Comment by DocDrydenn** [comment]
Sorry, that's not something I have tried, so I can't say for sure.

**Comment by sradityaa** [comment]
Oke, but is it possible to make dynamic build on android?

**Comment by sradityaa** [comment]
If so, what kind of command should I run?

**Comment by DocDrydenn** [comment]
I'm not exactly sure what you are asking...

This script simply produces a Linux binary, meant to be run from within a Linux environment. It can build for a generic PC, ARMv7, or ARMv8 CPU.

This script will not build a native android app/binary/package, if that's what you're asking...

Now, with that said, if you've installed something like `Linux Deploy` on your android device, then yes, this script will work on that device from within that that Linux environment... just be sure to build against whichever CPU your android device has (ARMv7 or ARMv8).
